### ISSUE TITLE
simulink files are missing

### ISSUE THREAD

**Issue by MMudassirShakeel** [chrysostomos997/Modeling-and-Simulation-of-a-Quadcopter#1]
Hi thanks for this amazing model can you plz add the simulink model it will great help in learning thanks and regard

**Comment by chrysostomos997** [comment]
Good morning my friend , sure i can share it and explain it but i have to charge this . If you want free you can try to do it , follow the photos in repository . For the mathematical model i used this equations : 
![image](https://user-images.githubusercontent.com/70040026/230304492-5bdc3c30-980d-49a4-91c1-4915e2812504.png)

**Comment by MMudassirShakeel** [comment]
Hi thanks for your reply, actually I'm student brother but which you send
maybe it helps thanks any ways

**Comment by chrysostomos997** [comment]
sure i can provide you some

**Comment by MMudassirShakeel** [comment]
I appreciate brother if you can provide me complete model because I really
need it brother

**Comment by chrysostomos997** [comment]
Hello my friend !! 
i am Chrysostomos Intzempeis , i sent you an email as well. 
i've just seen that you have upload a video in youtube about my project (a gif) . 
I am asking you to remove the video or at least to mention that the project is mine in the description. 
Thank you !

**Comment by MMudassirShakeel** [comment]
hi brother, i understand your concern, i will mention your name or i can
remove video whatever you will say my brother

**Comment by MMudassirShakeel** [comment]
you are very talented person and im just a student who is struggling to
make something for myself, would you plz like me to join my channel? you
just need to give lectures or upload your projects video on my channel and
we will divide the earning 50/50. what do you think?

**Comment by chrysostomos997** [comment]
I have just uploaded the project for educational purposes. I don't want to earn money from my projects.  If you want to keep the video on your channel you have to mention my name and link my github otherwise you have to delete the video.

**Comment by MMudassirShakeel** [comment]
Alright sir, got it

**Comment by chrysostomos997** [comment]
I dont want to go further because you are a student but if there is no other solution i will make a specific report concerning your youtube channel which will lead to deletion .  Thank you for understaning!

**Comment by MMudassirShakeel** [comment]
[image: image.png]

**Comment by chrysostomos997** [comment]
Now it is ok i saw your link !

**Comment by chrysostomos997** [comment]
Everything is fine !

**Comment by MMudassirShakeel** [comment]
i have added your name and github

**Comment by MMudassirShakeel** [comment]
thanks

**Comment by chrysostomos997** [comment]
No problem !

**Comment by MMudassirShakeel** [comment]
can you plz share the simulink model to me

**Comment by MMudassirShakeel** [comment]
and plz if you have other projects kindly send me also, im a learner and
want to learn something new everyday

**Comment by chrysostomos997** [comment]
If you want i can explain to you in a meeting the models and how i created them . Unfortunatelly i cant send them for free. You can understand that i spent a lot of hours for my thesis.  If dont want to give money we can trade something else . For example you can create something for me and i can share to you staff

**Comment by MMudassirShakeel** [comment]
bro you already put this project on github but not uploaded simulink model,
actually as i said im struggling student i cant pay for it, its my humble
request if you can send me the project otherwise its okay no problem

**Comment by MMudassirShakeel** [comment]
Im working on some project if you say i will send them to you after
completion

**Comment by chrysostomos997** [comment]
Let me think and we will be in touch  !!

**Comment by MMudassirShakeel** [comment]
sure sir, its nice to talk to you

**Comment by MMudassirShakeel** [comment]
Dear Sir/Madam,

I hope this message finds you well.

My name is Muhammad Mudassir Shakeel, and I am a seasoned professional with
extensive experience in both academic writing and providing high-quality
solutions for a wide range of engineering projects. My expertise spans
across various software platforms, including MATLAB, Simulink, CATIA,
SolidWorks, ANSYS, Fusion 360, Autodesk Inventor, CoppeliaSim, and COMSOL,
among others.

Over the years, I have had the privilege of assisting numerous clients
through platforms like Upwork and Fiverr, where I have successfully
delivered:

   - *Custom engineering solutions*: From complex simulations in MATLAB and
   Simulink to detailed designs in SolidWorks and Fusion 360.
   - *Technical writing*: High-quality, well-researched thesis papers,
   research articles, and assignment solutions tailored to meet academic and
   industry standards.
   - *Project support*: Comprehensive project guidance and implementation
   using advanced tools like ANSYS for FEA, COMSOL for multiphysics
   simulations, and CoppeliaSim for robotics.

My commitment to excellence and my broad technical skills have consistently
earned me top reviews and recognition as a Rising Talent on Upwork.

*Why Choose My Services?*

   - *Comprehensive Expertise*: Advanced knowledge and hands-on experience
   across a wide range of engineering software and academic writing
   disciplines.
   - *Innovative Solutions*: Tailored, cutting-edge solutions that meet the
   specific needs of your projects, whether academic or industrial.
   - *Reliability*: A proven track record of delivering accurate,
   high-quality work on time, ensuring your project goals are met.
   - *Effective Communication*: Clear and consistent communication
   throughout the project lifecycle, ensuring alignment with your vision.

I am confident that my diverse skills and experience can add significant
value to your projects, whether they involve complex engineering challenges
or high-stakes academic writing. I would love the opportunity to discuss
how we can collaborate to bring your ideas to life. Please feel free to
reply to this email or contact me directly via WhatsApp.

Thank you for considering my services. I look forward to the possibility of
working together.

Best regards,
Muhammad Mudassir Shakeel
Engineering Solutions Expert & Academic Writer

📌 Website <https://engrprogrammer.com/>
📌 YouTube Channel <https://youtu.be/fDGz7Ebudgc?si=ec7UV0A44t16Umx4>
📌 WhatsApp: +923096078248
📌 Instagram <https://www.instagram.com/engrprogrammer2494/>
-- 

Engr. Mudassir
Mechatronics & Control Engineer
E: ***@***.***
M: +923096078248
A: @engrprogrammer
www.engrprogrammer.com [image: youtube icon]
<https://www.youtube.com/channel/UCeeDj30c47LL4Hdp3I-NSsw> [image:
instagram icon] <https://www.instagram.com/engrprogrammer2494/>

The content of this email is confidential and intended for the recipient
specified in message only. It is strictly forbidden to share any part of
this message with any third party, without a written consent of the sender.
If you received this message by mistake, please reply to this message and
follow with its deletion, so that we can ensure such a mistake does not
occur in the future.
